PG_VETE_SMP/Controllers/DIRECCIONController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Capa_Datos;

namespace PG_VETE_SMP.Controllers
{
    public class DIRECCIONController : Controller
    {
        private RH_VETE_SMPEntities db = new RH_VETE_SMPEntities();

        // GET: DIRECCION
        public ActionResult Index()
        {
            var dIRECCION = db.DIRECCION.Include(d => d.DISTRITO);
            return View(dIRECCION.ToList());
        }
        public ActionResult GuardarDireccion(Capa_Datos.DIRECCION direccion)
        {
            PERSONA Person = new PERSONA();
            db.DIRECCION.Add(direccion);
            db.SaveChanges();
            Person.ID_DIRECCION = direccion.ID_DIRECCION;
            var dIRECCION = db.DIRECCION.Include(d => d.DISTRITO);
            return RedirectToAction("../PERSONAs/Create");   
        }
        // GET: DIRECCION/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DIRECCION dIRECCION = db.DIRECCION.Find(id);
            if (dIRECCION == null)
            {
                return HttpNotFound();
            }
            return View(dIRECCION);
        }

        // GET: DIRECCION/Create
        public ActionResult Create()
        {
            ViewBag.ID_DISTRITO = new SelectList(db.DISTRITO, "ID_DISTRITO", "DESCRIPCION");
            return View();
        }

        // POST: DIRECCION/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_DIRECCION,ID_DISTRITO,OTRAS_SENAS")] DIRECCION dIRECCION)
        {
            if (ModelState.IsValid)
            {
                db.DIRECCION.Add(dIRECCION);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_DISTRITO = new SelectList(db.DISTRITO, "ID_DISTRITO", "DESCRIPCION", dIRECCION.ID_DISTRITO);
            return View(dIRECCION);
        }

        // GET: DIRECCION/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DIRECCION dIRECCION = db.DIRECCION.Find(id);
            if (dIRECCION == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_DISTRITO = new SelectList(db.DISTRITO, "ID_DISTRITO", "DESCRIPCION", dIRECCION.ID_DISTRITO);
            return View(dIRECCION);
        }

        // POST: DIRECCION/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_DIRECCION,ID_DISTRITO,OTRAS_SENAS")] DIRECCION dIRECCION)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dIRECCION).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_DISTRITO = new SelectList(db.DISTRITO, "ID_DISTRITO", "DESCRIPCION", dIRECCION.ID_DISTRITO);
            return View(dIRECCION);
        }

        // GET: DIRECCION/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DIRECCION dIRECCION = db.DIRECCION.Find(id);
            if (dIRECCION == null)
            {
                return HttpNotFound();
            }
            return View(dIRECCION);
        }

        // POST: DIRECCION/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DIRECCION dIRECCION = db.DIRECCION.Find(id);
            db.DIRECCION.Remove(dIRECCION);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PG_VETE_SMP/Views/DIRECCION/Create.cshtml
@model Capa_Datos.DIRECCION

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("GuardarDireccion", "DIRECCION", FormMethod.Post, new { ID = "FORMULARIO_DIC" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DIRECCION</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_DISTRITO, "ID_DISTRITO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_DISTRITO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_DISTRITO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OTRAS_SENAS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OTRAS_SENAS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OTRAS_SENAS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PG_VETE_SMP/Views/DIRECCION/Delete.cshtml
@model Capa_Datos.DIRECCION

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DIRECCION</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OTRAS_SENAS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OTRAS_SENAS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DISTRITO.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DISTRITO.DESCRIPCION)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PG_VETE_SMP/Views/DIRECCION/Details.cshtml
@model Capa_Datos.DIRECCION

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DIRECCION</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OTRAS_SENAS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OTRAS_SENAS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DISTRITO.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DISTRITO.DESCRIPCION)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_DIRECCION }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PG_VETE_SMP/Views/DIRECCION/Edit.cshtml
@model Capa_Datos.DIRECCION

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DIRECCION</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_DIRECCION)

        <div class="form-group">
            @Html.LabelFor(model => model.ID_DISTRITO, "ID_DISTRITO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_DISTRITO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_DISTRITO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.OTRAS_SENAS, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.OTRAS_SENAS, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OTRAS_SENAS, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PG_VETE_SMP/Views/DIRECCION/Index.cshtml
@model IEnumerable<Capa_Datos.DIRECCION>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OTRAS_SENAS)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DISTRITO.DESCRIPCION)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OTRAS_SENAS)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DISTRITO.DESCRIPCION)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID_DIRECCION }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID_DIRECCION }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID_DIRECCION })
        </td>
    </tr>
}

</table>