PG_VETE_SMP/Controllers/USUARIOController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Capa_Datos;
using Microsoft.Ajax.Utilities;
using System.Windows;
using System.IO;

namespace PG_VETE_SMP.Controllers
{
    public class USUARIOController : Controller
    {
        private RH_VETE_SMPEntities db = new RH_VETE_SMPEntities();

        // GET: USUARIO
        public ActionResult Index()
        {
            var uSUARIO = db.USUARIO.Include(u => u.PERSONA).Include(u => u.TIPO_USUARIO);
            return View(uSUARIO.ToList());
        }

        public ActionResult Acceso()
        {

            return View("Acceso");

        }

        public ActionResult AccesoUsuario(USUARIO oUSUARIO)
        {
            
            var user = db.USUARIO.Find(oUSUARIO.NOMBRE_USUARIO);
            Session["NOMBRE_USUARIO"] = oUSUARIO.NOMBRE_USUARIO;
            Session["CONTRASENA"] = oUSUARIO.CONTRASENA;
            if (oUSUARIO.NOMBRE_USUARIO == user.NOMBRE_USUARIO)
            {
                if (oUSUARIO.CONTRASENA == user.CONTRASENA)
                {
                    
                    return View("../Home/Index");
                }
                else
                {
                    oUSUARIO.NOMBRE_USUARIO = "".ToString();
                    return View("Acceso");
                  
                }
            }
            else
            {
                return View("Acceso");
            }
        }

    }
}

PG_VETE_SMP/Views/USUARIO/Acceso.cshtml
@model Capa_Datos.USUARIO

@{
    ViewBag.Title = "Acceso";
}

<h2>Acceso</h2>

@using (Html.BeginForm("AccesoUSUARIO", "USUARIO", FormMethod.Post, new {ID="Formulario"}))
{
      
    <div class="form-horizontal">
        <h4>USUARIO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE_USUARIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE_USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE_USUARIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CONTRASENA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONTRASENA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONTRASENA, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ingresar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("NUEVO_USUARIO", "../Home/Index")
</div>

PG_VETE_SMP/Views/USUARIO/Create.cshtml
@model Capa_Datos.USUARIO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USUARIO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NOMBRE_USUARIO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NOMBRE_USUARIO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NOMBRE_USUARIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CONTRASENA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONTRASENA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONTRASENA, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PG_VETE_SMP/Views/USUARIO/Delete.cshtml
@model Capa_Datos.USUARIO

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>USUARIO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CONTRASENA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTRASENA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERSONA.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERSONA.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIPO_USUARIO.USUARIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIPO_USUARIO.USUARIO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PG_VETE_SMP/Views/USUARIO/Details.cshtml
@model Capa_Datos.USUARIO

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>USUARIO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CONTRASENA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTRASENA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ACTIVO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ACTIVO)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PERSONA.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PERSONA.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TIPO_USUARIO.USUARIO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TIPO_USUARIO.USUARIO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NOMBRE_USUARIO }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PG_VETE_SMP/Views/USUARIO/Edit.cshtml
@model Capa_Datos.USUARIO

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>USUARIO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.NOMBRE_USUARIO)

        <div class="form-group">
            @Html.LabelFor(model => model.CONTRASENA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CONTRASENA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CONTRASENA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ACTIVO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ACTIVO)
                    @Html.ValidationMessageFor(model => model.ACTIVO, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_USUARIO, "ID_USUARIO", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_USUARIO", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_USUARIO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CEDULA, "CEDULA", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CEDULA", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CEDULA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PG_VETE_SMP/Views/USUARIO/Index.cshtml
@model IEnumerable<Capa_Datos.USUARIO>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CONTRASENA)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ACTIVO)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PERSONA.NOMBRE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TIPO_USUARIO.USUARIO)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CONTRASENA)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ACTIVO)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PERSONA.NOMBRE)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TIPO_USUARIO.USUARIO)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.NOMBRE_USUARIO }) |
            @Html.ActionLink("Details", "Details", new { id=item.NOMBRE_USUARIO }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.NOMBRE_USUARIO })
        </td>
    </tr>
}

</table>